version: "3.8"
name: ${PROJECT_FOLDER_NAME:-apiato}
services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: ${PROJECT_FOLDER_NAME}_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PROJECT_VOLUME:?err}:delegated
#      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx.conf:/etc/nginx/templates/nginx.conf.template
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      PHP_HOST: ${PHP_VER:?err}
    depends_on:
      - ${PHP_VER:?err}
      - postgres
  php81:
    image: masmikh/php81:latest
    container_name: ${PROJECT_FOLDER_NAME}_php81
    user: '${UID}:${UID}'
    working_dir: ${WORKING_DIR:?err}
    volumes:
      - ${PROJECT_VOLUME:?err}:delegated
      - ./.composer:/.composer
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
  php82:
    image: masmikh/php82:latest
    container_name: ${PROJECT_FOLDER_NAME}_php82
    user: '${UID}:${UID}'
    working_dir: ${WORKING_DIR:?err}
    volumes:
      - ${PROJECT_VOLUME:?err}:delegated
      - ./.composer:/.composer
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
  php81_debug:
    build:
      context: dockerfiles
      dockerfile: php.dockerfile
      target: php81_debug
    image: masmikh/php81_debug:latest
    container_name: ${PROJECT_FOLDER_NAME}_php81_debug
    user: '${UID}:${UID}'
    working_dir: ${WORKING_DIR:?err}
    volumes:
      - ${PROJECT_VOLUME:?err}:delegated
      - ./.composer:/.composer
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_FOLDER_NAME}_mysql
    ports:
      - "3306:3306"
    env_file:
      - mysql/mysql.env
  postgres:
    image: postgres:latest
    container_name: ${PROJECT_FOLDER_NAME}_postgres
    restart: always
    user: '${UID}:${UID}'
    env_file:
      - postgres/postgres.env
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/conf:/etc/postgresql
      - ./postgres/log:/var/log/postgresql
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    container_name: ${PROJECT_FOLDER_NAME}_adminer
    restart: always
    ports:
      - "8090:8080"
  npm:
    build:
      context: .
      dockerfile: dockerfiles/node.dockerfile
    container_name: ${PROJECT_FOLDER_NAME}_npm
    entrypoint: [ "npm" ]
    volumes:
      - ${PROJECT_VOLUME:?err}:delegated
  node:
    build:
      context: .
      dockerfile: dockerfiles/node.dockerfile
    container_name: ${PROJECT_FOLDER_NAME}_node
    volumes:
      - ${PROJECT_VOLUME:?err}:delegated