version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports: 
      - '80:80'
    volumes: 
      - ${PROJECT_VOLUME}
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    user: '${UID}:${UID}'
    volumes: 
      - ${PROJECT_VOLUME}
  mysql:
    image: mysql:5.7
    env_file: 
      - ./mysql.env
  composer:
    image: composer:latest
    user: '${UID}:${UID}'
    working_dir: ${WORKING_DIR}
    entrypoint: [ "composer", "--ignore-platform-reqs" ]
    volumes:
      - ${PROJECT_VOLUME}
  artisan:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
      args:
        install_node: 1
    volumes:
      - ${PROJECT_VOLUME}
    entrypoint: ["php", "${WORKING_DIR}/artisan"]
  npm:
    image: node:14
    working_dir: ${WORKING_DIR}
    entrypoint: ["npm"]
    volumes: 
      - ${PROJECT_VOLUME}
  node:
    image: node:14
    working_dir: ${WORKING_DIR}
    volumes:
      - ${PROJECT_VOLUME}