CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE; GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%'; 
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE_TEST; GRANT ALL PRIVILEGES ON $MYSQL_DATABASE_TEST.* TO '$MYSQL_USER'@'%'; 
